#!/usr/bin/env bash
# Transfers a file from a client to a server using SCP
#
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

# Check if all required arguments are provided
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  # Transfer file using SCP with strict host key checking disabled
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
